Iter5
PanAndrei/URLShorter pull request #5
Opened 2024-12-01 21:29 UTC by PanAndrei

2024-12-03 21:08 UTC, avhitrov requested changes
Есть некоторое количество замечаний - в комментариях к коду.

2024-12-03 21:08 UTC, avhitrov commented on internal/app/config/flags/flags.go
> +	flag.Parse()
Значение параметров командной строки при таком расположении кода имеет приоритет перед переменными окружения. В задании - наоборот.

2024-12-03 21:08 UTC, avhitrov commented on internal/app/handlers/handlers.go
> +	r := newRouter(h)
```suggestion
	r := chi.NewRouter()
```
локальная функция `newRouter` только добавляет бессмысленную обертку над данным вызовом.

2024-12-03 21:08 UTC, avhitrov commented on internal/app/handlers/handlers.go
> +	}
Если озадачиваться закрытием прочитанного тела, то именно здесь необходимо поставить
```
defer req.Body.Close()
```

2024-12-03 21:08 UTC, avhitrov commented on internal/app/repository/repository.go
> +	store.s[u.FullURL] = u.ShortURL
Лучше сохранять наоборот. 
```suggestion
	store.s[u.ShortURL] = u.FullURL
```
Заданный метод применения - это получить по короткому идентификатору полный url и отправить пользователю редирект. Поиск по ключу однозначно быстрее (точнее не медленнее), чем полный перебор значений.

2024-12-03 21:43 UTC, PanAndrei commented on internal/app/repository/repository.go
> +	store.s[u.FullURL] = u.ShortURL
я думал об этом, но выбрал именно такое решение по следующей причине: 
если ключом будет короткий урл, то для того что бы при каждом пост запросе вида ya.ru 
не создавать кучу коротких урлов для одного и того же длинного, на мой взгляд, есть 2 пути - 
или поддерживать 2 мапы - что удвоит хранилище, или валидировать каждый входящий урл при пост запросе. я так и делаю тут.
если я применю предложенные изменения - то в этом месте цикл уйдет, а потом либо появится в момент присвоения короткого адреса, либо пропадет валидация на уникальность полного урла.

2024-12-04 10:52 UTC, PanAndrei commented on internal/app/config/flags/flags.go
> +	flag.Parse()
тут тоже не понятно почему - сначала записываются флаги + значение по дефолту - потом оно переписывается из конфига (окружения) если оно там есть.

2024-12-05 21:55 UTC, avhitrov commented on internal/app/config/flags/flags.go
> +	flag.Parse()
Именно. flag.Parse() занимается фактически проведением описанных ранее действий.

2024-12-05 22:02 UTC, avhitrov approved these changes
Аппрув, но в следующей итерации необходимо исправить положение defer. Комментарий - в коде.

2024-12-05 22:02 UTC, avhitrov commented on internal/app/handlers/handlers.go
> +	defer req.Body.Close()
Вот здесь defer ставить однозначно не следует. Его место всегда после проверки возможной ошибки.

Подробности:
https://t.me/bushigo/21

2024-12-05 22:02 UTC, avhitrov commented on internal/app/repository/repository.go
> +	store.s[u.FullURL] = u.ShortURL
Можно сделать две взаимно направленных мапы: в одной ключом сделать короткий url, во второй - длинный. Но при этом придется озадачиться синхронным и транзакционно безопасным их изменением. Но в данном случае я не буду настаивать на выборе своего варианта, объяснение принято, если реализация начнет мешать - ты просто сам отрефакторишь код.

2024-12-07 07:23 UTC, merged